export interface Project {
  id: string
  name: string
  description: string
  category: string
  imageUrl: string
  website?: string
  twitter?: string
  fundingGoal?: number
  fundingCurrent?: number
  likes?: number
  comments?: number
  walletAddress?: string
  isBookmarked?: boolean
  userHasLiked?: boolean
  userHasCommented?: boolean
  reportCount?: number
  boostAmount?: number
}

export const categories = ["Digital Art", "Installation", "Community", "Gaming", "Education", "Events", "Talent"]

export const projects: Project[] = [
  // Digital Art Projects
  {
    id: "project-1",
    name: "Floppy Disc Head",
    description: "A unique digital art piece featuring a retro floppy disc head design in the classic Nouns aesthetic.",
    category: "Digital Art",
    imageUrl: "https://i.noundry.wtf/JX12wARXJ/preview.png",
    twitter: "https://x.com/Fattybuthappyy",
    fundingGoal: 15000,
    fundingCurrent: 8500,
    likes: 124,
    comments: 18,
    walletAddress: "0xedc1a397589a0236c4810883b7d559288a5fe7e1",
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-2",
    name: "3D X mETH",
    description: "Innovative 3D digital art exploring the intersection of Nouns culture and blockchain technology.",
    category: "Digital Art",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmdQVi6EPRvBNsb2YcNu5DhWXuRbHwQ8LifWXsJ318XCNW?img-width=500&img-onerror=redirect",
    website: "https://nouns.gg/c/mantle/rounds/cooking-bad?p=174839f1-fc55-4867-b223-86f2a59c0920",
    fundingGoal: 20000,
    fundingCurrent: 12000,
    likes: 89,
    comments: 12,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-3",
    name: "Pixels by Kay",
    description: "Pixel art creations that capture the essence of Nouns through detailed digital craftsmanship.",
    category: "Digital Art",
    imageUrl: "https://imagedelivery.net/BXluQx4ige9GuW0Ia56BHw/c3e060d4-a43e-4bfa-3f64-29879c8d5600/original",
    website: "https://warpcast.com/pixelsbykay",
    fundingGoal: 12000,
    fundingCurrent: 7500,
    likes: 156,
    comments: 24,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-4",
    name: "Abstract Noun - Glow",
    description: "An abstract interpretation of Nouns featuring luminous glow effects and modern digital aesthetics.",
    category: "Digital Art",
    imageUrl:
      "https://i2.seadn.io/ethereum/0x495f947276749ce646f68ac8c248420045cb7b5e/1d383edf7ae0dcfc45634d9a79c7c4/751d383edf7ae0dcfc45634d9a79c7c4.png?w=1000",
    fundingGoal: 18000,
    fundingCurrent: 9200,
    likes: 203,
    comments: 31,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },

  // Installation Projects
  {
    id: "project-5",
    name: "Noun City",
    description:
      "A large-scale physical installation bringing Nouns into the real world through urban art and community spaces.",
    category: "Installation",
    imageUrl: "https://cdn.sanity.io/images/5ujarpl0/staging/9e1d34e86bb2a929b6434689adc36b18f5fc8370-874x946.webp",
    fundingGoal: 75000,
    fundingCurrent: 42000,
    likes: 342,
    comments: 67,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },

  // Community Projects
  {
    id: "project-6",
    name: "Nouns Univers",
    description:
      "Building a comprehensive universe for Nouns community members to connect, collaborate, and create together.",
    category: "Community",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmVP1zQMzJtojsTLD8X4rnWyb4ErnumYqV4J2Ke8XTLCk8?img-width=500&img-onerror=redirect",
    fundingGoal: 45000,
    fundingCurrent: 28000,
    likes: 289,
    comments: 45,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-7",
    name: "NatalieCrue for Delegate",
    description: "Supporting community leadership and governance participation within the Nouns ecosystem.",
    category: "Community",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/Qmbx1wK7QxXEmYtDbRKiGjkfCpcf6nHhdiNJwqDUMPoTjX?img-width=500&img-onerror=redirect",
    fundingGoal: 25000,
    fundingCurrent: 15000,
    likes: 178,
    comments: 29,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-8",
    name: "Abacus Head",
    description: "A community-driven project celebrating mathematical thinking and problem-solving in the Nouns style.",
    category: "Community",
    imageUrl: "https://hackmd.io/_uploads/BJIEdJsVlg.png",
    fundingGoal: 20000,
    fundingCurrent: 11500,
    likes: 134,
    comments: 22,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-9",
    name: "Silly Goose Accessory",
    description:
      "Fun and whimsical accessories for the Nouns community, bringing joy and playfulness to the ecosystem.",
    category: "Community",
    imageUrl: "https://i.noundry.wtf/l4J1H85RR/preview.png",
    fundingGoal: 15000,
    fundingCurrent: 8200,
    likes: 167,
    comments: 25,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },

  // Gaming Projects
  {
    id: "project-10",
    name: "BubbleGum Nouns",
    description: "A colorful and engaging game featuring Nouns characters in a bubble-popping adventure.",
    category: "Gaming",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmQnRGXXkrYKQEXUyPXDoSjTqqnqz2qwbCF3BKY8YTc5bi?img-width=500&img-onerror=redirect",
    fundingGoal: 35000,
    fundingCurrent: 18500,
    likes: 245,
    comments: 38,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-11",
    name: "Merge the Nouns",
    description:
      "A puzzle game where players merge different Noun traits to create unique combinations and unlock rewards.",
    category: "Gaming",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmQtzXgzQyDc8tzk1UnD6LzGUQNrADZjmqCF2fyp9R9Xnr?img-width=500&img-onerror=redirect",
    fundingGoal: 28000,
    fundingCurrent: 16000,
    likes: 198,
    comments: 31,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-12",
    name: "Pika Nouns",
    description: "An adventure game combining the beloved Pokémon-style gameplay with Nouns characters and mechanics.",
    category: "Gaming",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmQLUbBhnSkaZ785WUt75CwW1ZiWXsvVCGW5KwKmDfscaL?img-width=500&img-onerror=redirect",
    fundingGoal: 42000,
    fundingCurrent: 25000,
    likes: 356,
    comments: 54,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-13",
    name: "Happy Nounish Ninja",
    description: "A fast-paced action game featuring ninja Nouns with special abilities and challenging levels.",
    category: "Gaming",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmZsq2HNapGBuwNxkjAUd6nAdB6cQ2i4gpqcDDuVdrAnTC?img-width=500&img-onerror=redirect",
    fundingGoal: 32000,
    fundingCurrent: 19500,
    likes: 223,
    comments: 35,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-14",
    name: "Nouns Math Runner",
    description:
      "An educational running game that teaches math concepts while players navigate through Nouns-themed obstacles.",
    category: "Gaming",
    imageUrl:
      "https://ipfs.nouns.gg/ipfs/QmWEhoLecLZiQbrKZYhdGCmA28L9efWumRxXPPdz6GFiog?img-width=500&img-onerror=redirect",
    fundingGoal: 25000,
    fundingCurrent: 14000,
    likes: 189,
    comments: 28,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },

  // Education Projects
  {
    id: "project-15",
    name: "Nouns Piggy Bank Booth",
    description:
      "Teaching financial literacy and saving habits to children through interactive Nouns-themed educational experiences.",
    category: "Education",
    imageUrl: "https://x.com/Degudhadharma/status/1966895546238726359/photo/2",
    twitter: "https://x.com/Degudhadharma",
    fundingGoal: 30000,
    fundingCurrent: 18000,
    likes: 267,
    comments: 42,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },

  // Events Projects
  {
    id: "project-16",
    name: "Urbe Village 2025",
    description:
      "A community gathering and festival celebrating Nouns culture with workshops, talks, and collaborative activities.",
    category: "Events",
    imageUrl: "https://ipfs.skatehive.app/ipfs/QmbB6dhXiexZ1TB1KeECc5oUHX4Qzx2u2hTkXRppUGaZgt",
    website: "https://www.nouns.camp/proposals/847",
    fundingGoal: 85000,
    fundingCurrent: 52000,
    likes: 445,
    comments: 78,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-17",
    name: "Nouns @ DevCon 2025",
    description:
      "Representing the Nouns community at the premier Ethereum developer conference with talks, demos, and networking.",
    category: "Events",
    imageUrl: "https://hackmd.io/_uploads/HyWpw3y5gg.jpg",
    fundingGoal: 65000,
    fundingCurrent: 38000,
    likes: 312,
    comments: 56,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },

  // Talent Projects
  {
    id: "project-18",
    name: "Metamonk",
    description:
      "Supporting talented community member Metamonk in their contributions to the Nouns ecosystem and Web3 development.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=0",
    twitter: "https://twitter.com/m3tamonk",
    fundingGoal: 40000,
    fundingCurrent: 24000,
    likes: 198,
    comments: 33,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-19",
    name: "Soondooboop",
    description:
      "Recognizing and supporting the creative contributions of Soondooboop to the Nouns community and broader ecosystem.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=1",
    twitter: "https://twitter.com/soondooboop",
    fundingGoal: 35000,
    fundingCurrent: 21000,
    likes: 167,
    comments: 29,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-20",
    name: "Christian",
    description:
      "Supporting Christian's ongoing work and innovation within the Nouns ecosystem and decentralized technology space.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=2",
    twitter: "https://twitter.com/cdt_eth",
    fundingGoal: 45000,
    fundingCurrent: 28000,
    likes: 234,
    comments: 41,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-21",
    name: "Brian",
    description:
      "Supporting Brian's creative and technical contributions to the Nouns community and decentralized ecosystem.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=3",
    twitter: "https://twitter.com/pbrianandj",
    fundingGoal: 38000,
    fundingCurrent: 22500,
    likes: 156,
    comments: 27,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-22",
    name: "Brushee",
    description:
      "Recognizing Brushee's artistic talents and ongoing contributions to the visual identity of the Nouns ecosystem.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=4",
    twitter: "https://twitter.com/brushee128",
    fundingGoal: 32000,
    fundingCurrent: 19000,
    likes: 143,
    comments: 24,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-23",
    name: "Kiran Cherukuri",
    description:
      "Supporting Kiran Cherukuri's innovative work in neuroscience and technology within the Nouns community.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=5",
    twitter: "https://twitter.com/neuroswish",
    fundingGoal: 42000,
    fundingCurrent: 26000,
    likes: 189,
    comments: 35,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-24",
    name: "Forager",
    description:
      "Recognizing Forager's research and development contributions to the Nouns ecosystem and Web3 infrastructure.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=6",
    twitter: "https://twitter.com/_forager",
    fundingGoal: 36000,
    fundingCurrent: 21500,
    likes: 172,
    comments: 31,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
  {
    id: "project-25",
    name: "Ripe",
    description:
      "Supporting Ripe's creative engine and innovative projects that push the boundaries of the Nouns ecosystem.",
    category: "Talent",
    imageUrl: "https://api.cloudnouns.com/v1/pfp?ref=nounscenter&utm_source=7",
    twitter: "https://twitter.com/unripeengine",
    fundingGoal: 39000,
    fundingCurrent: 23500,
    likes: 164,
    comments: 28,
    isBookmarked: false,
    userHasLiked: false,
    userHasCommented: false,
    reportCount: 0,
    boostAmount: 0,
  },
]
